version: "3"

services:
    platform:
        image: node:12.18.4-stretch-slim
        container_name: platform
        working_dir: /dsm/platform/
        command: yarn start
        volumes:
            - ./:/dsm/platform/:consistent
        ports:
            - 3000:3000

networks:
    default:
        external:
            name: dsm_network
